// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OWuffel.Extensions.Database;

namespace OWuffel.Migrations
{
    [DbContext(typeof(WuffelDBContext))]
    [Migration("20210912101548_NameConventionNormalization")]
    partial class NameConventionNormalization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("OWuffel.Models.BotSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("BotActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("BotAdminRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("BotClearMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("BotClearMessagesForBot")
                        .HasColumnType("boolean");

                    b.Property<string>("BotDisabledCommands")
                        .HasColumnType("text");

                    b.Property<string>("BotLanguage")
                        .HasColumnType("text");

                    b.Property<decimal>("BotModRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("BotMuteRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("BotPrefix")
                        .HasColumnType("text");

                    b.Property<bool>("BotSystemNotice")
                        .HasColumnType("boolean");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("OWuffel.Models.DailyRankingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("IgnoreId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("DailyRankingConfig");
                });

            modelBuilder.Entity("OWuffel.Models.GuildInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("GuildAvatar")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GuildName")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildOwnerId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GuildOwnerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GuildInformations");
                });

            modelBuilder.Entity("OWuffel.Models.LogsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("LogChannelEvents")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("LogChannelPowerSwitch")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LogEmoteEvents")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("LogEmotePowerSwitch")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LogGuildUpdated")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LogIgnoreMessageEvents")
                        .HasColumnType("text");

                    b.Property<string>("LogIgnoreVoiceStateUpdated")
                        .HasColumnType("text");

                    b.Property<decimal>("LogMessageEvents")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("LogMessageEventsPowerSwitch")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LogRoleEvents")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("LogRolePowerSwtich")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LogUserMovement")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("LogUserMovementPowerSwitch")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LogUserUpdated")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("LogUserUpdatedPowerSwitch")
                        .HasColumnType("boolean");

                    b.Property<bool>("LogVoicePresencePowerSwitch")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LogVoiceStateUpdated")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("LogsConfigs");
                });

            modelBuilder.Entity("OWuffel.Models.ReactionsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ReactServerChannel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ReactServerMessage")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ReactServerParent")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("ReactionsConfigs");
                });

            modelBuilder.Entity("OWuffel.Models.Suggestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Moderator")
                        .HasColumnType("text");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<int>("VoteDislike")
                        .HasColumnType("integer");

                    b.Property<int>("VoteLike")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("OWuffel.Models.SuggestionsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("SuggestionChannel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("SuggestionLogChannel")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("SuggestionsConfigs");
                });

            modelBuilder.Entity("OWuffel.Models.SupportConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("ActiveTicketsId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Notify")
                        .HasColumnType("integer");

                    b.Property<decimal>("ParentId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("PremiumStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("TicketInfoId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("TicketMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("SupportConfigs");
                });

            modelBuilder.Entity("OWuffel.Models.Tickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WhoClosedTicket")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("OWuffel.Models.WelcomeMessageConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WelcomeChannel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("WelcomeMessageAutoDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("WelcomeMessageConfigs");
                });

            modelBuilder.Entity("OWuffel.Models.BotSettings", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("BotSettings")
                        .HasForeignKey("OWuffel.Models.BotSettings", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.DailyRankingConfig", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("DailyRankingConfig")
                        .HasForeignKey("OWuffel.Models.DailyRankingConfig", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.LogsConfig", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("LogsConfig")
                        .HasForeignKey("OWuffel.Models.LogsConfig", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.ReactionsConfig", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("ReactionsConfig")
                        .HasForeignKey("OWuffel.Models.ReactionsConfig", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.Suggestions", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("Suggestions")
                        .HasForeignKey("OWuffel.Models.Suggestions", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.SuggestionsConfig", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("SuggestionsConfig")
                        .HasForeignKey("OWuffel.Models.SuggestionsConfig", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.SupportConfig", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("SupportConfig")
                        .HasForeignKey("OWuffel.Models.SupportConfig", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.Tickets", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("Tickets")
                        .HasForeignKey("OWuffel.Models.Tickets", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.WelcomeMessageConfig", b =>
                {
                    b.HasOne("OWuffel.Models.GuildInformation", "GuildInformation")
                        .WithOne("WelcomeMessageConfig")
                        .HasForeignKey("OWuffel.Models.WelcomeMessageConfig", "GuildId")
                        .HasPrincipalKey("OWuffel.Models.GuildInformation", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInformation");
                });

            modelBuilder.Entity("OWuffel.Models.GuildInformation", b =>
                {
                    b.Navigation("BotSettings");

                    b.Navigation("DailyRankingConfig");

                    b.Navigation("LogsConfig");

                    b.Navigation("ReactionsConfig");

                    b.Navigation("Suggestions");

                    b.Navigation("SuggestionsConfig");

                    b.Navigation("SupportConfig");

                    b.Navigation("Tickets");

                    b.Navigation("WelcomeMessageConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
