// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OWuffel.Extensions.Database;

namespace OWuffel.Migrations
{
    [DbContext(typeof(WuffelDBContext))]
    partial class WuffelDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("OWuffel.Extensions.Database.ChannelCheckModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channels")
                        .HasColumnType("TEXT");

                    b.Property<string>("Found")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChannelChecks");
                });

            modelBuilder.Entity("OWuffel.Extensions.Database.DailyRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoreId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DailyRankings");
                });

            modelBuilder.Entity("OWuffel.Extensions.Database.Settings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("botActive")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("botAdminRole")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("botClearMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("botClearMessagesForBot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("botDisabledCommands")
                        .HasColumnType("TEXT");

                    b.Property<string>("botLanguage")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("botModRole")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("botMuteRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("botPrefix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("botSystemNotice")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("guild_id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logChannelCreated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logChannelDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logChannelUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logEmoteCreated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logEmoteDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logEmoteUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logGuildUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("logIgnoreMessageDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("logIgnoreMessageUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("logIgnoreVoiceStateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("logMessageDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logMessageUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logRoleCreated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logRoleDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logRoleUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logUserBanned")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logUserJoined")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logUserLeft")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logUserUnbanned")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logUserUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("logVoiceStateUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("reactServerChannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("reactServerMessage")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("reactServerParent")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("suggestionChannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("suggestionLogChannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("welcomeChannel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("welcomeMessageAutoDelete")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("guild_id")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("OWuffel.Extensions.Database.Suggestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moderator")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteDislike")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteLike")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("OWuffel.Extensions.Database.SupportConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ActiveTicketsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Notify")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PremiumStatus")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TicketInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SupportConfiguration");
                });

            modelBuilder.Entity("OWuffel.Extensions.Database.Tickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("WhoClosedTicket")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
